makeobj pak128 ./pak/ ./appliance/
makeobj pak128 ./pak/ ./beer/
makeobj pak128 ./pak/ ./car/
makeobj pak128 ./pak/ ./cement/
makeobj pak128 ./pak/ ./coal/
makeobj pak128 ./pak/ ./grain
makeobj pak128 ./pak/ ./oil/
makeobj pak128 ./pak/ ./smoke/
makeobj pak128 ./pak/ ./steel/
makeobj pak128 ./pak/ ./
